name: Manual Build and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Release tag (e.g. v1.0.0)"
        required: true
      release_name:
        description: "Release name (e.g. Network Tool v1.0.0)"
        required: true

jobs:
  release:
    runs-on: windows-latest
    name: Build EXE and publish release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PS2EXE
        run: |
          Install-Module -Name ps2exe -Force -Scope CurrentUser -AllowClobber
        shell: pwsh

      - name: Convert .ps1 to .exe
        run: |
          $Input = "NetworkProfileManager.ps1"
          $Output = "NetworkProfileManager.exe"
          Invoke-PS2EXE -InputFile $Input -OutputFile $Output -NoConsole
        shell: pwsh

      - name: Create ZIP file
        run: |
          Compress-Archive -Path NetworkProfileManager.exe -DestinationPath NetworkProfileManager.zip
        shell: pwsh

      - name: Create GitHub Release and upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name }}
          files: NetworkProfileManager.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
